import os
from dotenv import load_dotenv

load_dotenv()


class Config:
    LOCAL_POSTGRESQL_USER = os.getenv("LOCAL_POSTGRESQL_USER")
    LOCAL_POSTGRESQL_PASSWORD = os.getenv("LOCAL_POSTGRESQL_PASSWORD")
    LOCAL_POSTGRESQL_DATABASE = os.getenv("LOCAL_POSTGRESQL_DATABASE")
    LOCAL_POSTGRESQL_HOST = os.getenv("LOCAL_POSTGRESQL_HOST")
    PGADMIN_EMAIL = os.getenv("PGADMIN_EMAIL")
    PGADMIN_PASSWORD = os.getenv("PGADMIN_PASSWORD")
    RABBITMQ_DEFAULT_USER = os.getenv("RABBITMQ_DEFAULT_USER")
    RABBITMQ_DEFAULT_PASS = os.getenv("RABBITMQ_DEFAULT_PASS")
    RABBITMQ_DEFAULT_HOST = os.getenv("RABBITMQ_DEFAULT_HOST")
    MIDDLEWARE_SECRET_KEY = os.getenv("MIDDLEWARE_SECRET_KEY")
